spring:
  data:
    mongodb:
      uri: ${QUIZ_DB_URL}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_URL}
jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
url:
  frontend: https://quizit.org
  service:
    auth: auth-service/api/auth
    user: user-service/api/user
    quiz: quiz-service/api/quiz